{
	"version": 1618272130,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/chao-sheet0.png",
		"images/cenario-sheet0.png",
		"images/medio-sheet0.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/opçao-sheet0.png",
		"images/fundodemensagem-sheet0.png",
		"images/caixa1-sheet0.png",
		"images/caixa1-sheet1.png",
		"images/bolaa-sheet0.png",
		"images/particles.png",
		"images/fundodateladeniveis-sheet0.png",
		"images/cenario2-sheet0.png",
		"images/fruta-sheet0.png",
		"images/igual-sheet0.png",
		"images/respostas-sheet0.png",
		"images/respostas-sheet1.png",
		"images/menos-sheet0.png",
		"images/colisor-sheet0.png",
		"images/fases1-sheet0.png",
		"images/fases1-sheet1.png",
		"images/fase2-sheet0.png",
		"images/fase2-sheet1.png",
		"images/fase3-sheet0.png",
		"images/fase3-sheet1.png",
		"images/seta-sheet0.png",
		"images/seta-sheet1.png",
		"images/cenario3-sheet0.png",
		"images/splash-sheet0.png",
		"images/telademenu-sheet0.png",
		"images/play-sheet0.png",
		"images/creditos-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/fundopreto-sheet0.png",
		"images/logo-sheet0.png",
		"images/carregamento-sheet0.png",
		"images/barrabranca.png",
		"images/spritefont.png",
		"images/barrabran-sheet0.png",
		"images/proximo-sheet0.png",
		"images/pedras-sheet0.png",
		"images/pedras-sheet1.png",
		"images/pedras2-sheet0.png",
		"images/arvore-sheet0.png",
		"images/quadro-sheet0.png",
		"images/lafora.png",
		"images/menu-sheet0.png",
		"images/menu-sheet1.png",
		"images/quadro2-sheet0.png",
		"images/tela-sheet0.png",
		"images/sensro-sheet0.png",
		"images/ponto-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/fundo-sheet0.png",
		"images/fundo-sheet1.png",
		"images/fundo-sheet2.png",
		"images/fundo-sheet3.png",
		"images/fundo-sheet4.png",
		"images/fundo-sheet5.png",
		"images/fundo-sheet6.png",
		"images/fundo-sheet7.png",
		"images/fundo-sheet8.png",
		"images/fundo-sheet9.png",
		"images/fundo-sheet10.png",
		"images/fundo-sheet11.png",
		"images/fundo-sheet12.png",
		"images/fundo-sheet13.png",
		"images/fundo-sheet14.png",
		"images/fundo-sheet15.png",
		"images/fundo-sheet16.png",
		"images/fundo-sheet17.png",
		"images/fundo-sheet18.png",
		"images/fundo-sheet19.png",
		"images/fundo-sheet20.png",
		"images/fundo-sheet21.png",
		"images/fundo-sheet22.png",
		"images/fundo-sheet23.png",
		"images/fundo-sheet24.png",
		"images/fundo-sheet25.png",
		"images/fundo-sheet26.png",
		"images/fundo-sheet27.png",
		"images/fundo-sheet28.png",
		"images/fundo-sheet29.png",
		"images/fundo-sheet30.png",
		"images/fundo-sheet31.png",
		"images/fundo-sheet32.png",
		"images/fundo-sheet33.png",
		"images/fundo-sheet34.png",
		"images/fundo-sheet35.png",
		"images/fundo-sheet36.png",
		"images/fundo-sheet37.png",
		"images/fundo-sheet38.png",
		"images/fundo-sheet39.png",
		"images/fundo-sheet40.png",
		"images/fundo-sheet41.png",
		"images/fundo-sheet42.png",
		"images/fundo-sheet43.png",
		"images/fundo-sheet44.png",
		"images/fundo-sheet45.png",
		"images/fundo-sheet46.png",
		"images/fundo-sheet47.png",
		"images/fundo-sheet48.png",
		"images/fundo-sheet49.png",
		"images/fundo-sheet50.png",
		"images/fundo-sheet51.png",
		"images/fundo-sheet52.png",
		"images/fundodemensagem2-sheet0.png",
		"images/son-sheet0.png",
		"images/son-sheet1.png",
		"images/musica-sheet0.png",
		"images/musica-sheet1.png",
		"images/musica-sheet2.png",
		"images/simbolo-sheet0.png",
		"images/simbolo-sheet1.png",
		"images/simbolo-sheet2.png",
		"images/simbolo-sheet3.png",
		"images/simbolo-sheet4.png",
		"images/simbolo-sheet5.png",
		"images/simbolo-sheet6.png",
		"images/simbolo-sheet7.png",
		"images/simbolo-sheet8.png",
		"images/simbolo-sheet9.png",
		"images/simbolo-sheet10.png",
		"images/simbolo-sheet11.png",
		"images/simbolo-sheet12.png",
		"images/simbolo-sheet13.png",
		"images/simbolo-sheet14.png",
		"images/simbolo-sheet15.png",
		"images/simbolo-sheet16.png",
		"images/simbolo-sheet17.png",
		"images/simbolo-sheet18.png",
		"images/simbolo-sheet19.png",
		"images/simbolo-sheet20.png",
		"images/simbolo-sheet21.png",
		"images/simbolo-sheet22.png",
		"images/simbolo-sheet23.png",
		"images/simbolo-sheet24.png",
		"images/simbolo-sheet25.png",
		"images/simbolo-sheet26.png",
		"images/simbolo-sheet27.png",
		"images/simbolo-sheet28.png",
		"images/simbolo-sheet29.png",
		"images/logoooo-sheet0.png",
		"images/logoooo-sheet1.png",
		"images/logoooo-sheet2.png",
		"images/logoooo-sheet3.png",
		"images/logoooo-sheet4.png",
		"images/logoooo-sheet5.png",
		"images/logoooo-sheet6.png",
		"images/logoooo-sheet7.png",
		"images/logoooo-sheet8.png",
		"images/logoooo-sheet9.png",
		"images/logoooo-sheet10.png",
		"images/logoooo-sheet11.png",
		"images/logoooo-sheet12.png",
		"images/logoooo-sheet13.png",
		"images/x-sheet0.png",
		"images/sc-sheet0.png",
		"images/confic-sheet0.png",
		"images/ttt-sheet0.png",
		"images/som-sheet0.png",
		"images/som-sheet1.png",
		"images/clik-sheet0.png",
		"images/clik-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/fundodeparabens-sheet0.png",
		"images/parabens-sheet0.png",
		"media/00.ogg",
		"media/01.ogg",
		"media/02.ogg",
		"media/03.ogg",
		"media/04.ogg",
		"media/05.ogg",
		"media/06.ogg",
		"media/07.ogg",
		"media/08.ogg",
		"media/09.ogg",
		"media/010.ogg",
		"media/explicação da subtração.ogg",
		"media/qcficaram.ogg",
		"media/quantascaixas.ogg",
		"media/retirada das caixas.ogg",
		"media/frutas.ogg",
		"media/4frutas.ogg",
		"media/5 frusta.ogg",
		"media/6frutas.ogg",
		"media/mensagem de erro.ogg",
		"media/quantas frutas ainda sobrou.ogg",
		"media/vc tinha 12.ogg",
		"media/vc tinha 10.ogg",
		"media/vc tinha 8.ogg",
		"media/parabéns.ogg",
		"media/clik.ogg",
		"media/clik1.ogg",
		"media/clik2.ogg",
		"media/clik3.ogg",
		"media/pedraretiras.ogg",
		"media/primeira coluna.ogg",
		"media/segunda coluna.ogg",
		"media/son fundo.ogg",
		"media/182683__bigfriendlyjiant__lake-st-clair-1.m4a",
		"media/182683__bigfriendlyjiant__lake-st-clair-1.ogg",
		"media/click sobre as caixas para retiralas até miguel pegar sua amiga bola.ogg",
		"media/rc.ogg",
		"media/“excelente, agora miguel já consegue alcançar. clique sobre  o número que indica quantas caixas retaram”.ogg",
		"media/parabéns você sabia  que acabou de realizar uma subtração.ogg",
		"media/tinha 10 frutas tirou 5.ogg",
		"media/tinha 12 frutas tirou 6.ogg",
		"media/tinha 8 frutas tirou 4.ogg",
		"media/miguel esta com fome tire 4.ogg",
		"media/miguel esta com fome tire 5 frutas.ogg",
		"media/miguel esta com fome tire 6 frutas.ogg",
		"media/parabens isso mesmo.ogg",
		"media/quantas frutas vc vê na arvore.ogg",
		"media/011.ogg",
		"media/012.ogg",
		"media/013.ogg",
		"media/014.ogg",
		"media/015.ogg",
		"media/016.ogg",
		"media/“quanta sorte!!! miguel está faminto e encontrou uma árvore com muitas frutas, conte  quantas são. se necessário clique sobre cada uma delas para obter ajuda. ”.ogg",
		"media/e agora_ qual o resultado da operação_.ogg",
		"media/ops ainda n é a resposta certa tente de novo.ogg",
		"media/quantas pedras temos na primeira  coluna.ogg",
		"media/quantas pedras temos na segunda coluna.ogg",
		"media/quantas pedras vc precisou retirar.ogg",
		"media/retire algumas pedras2.ogg",
		"media/ebbaaa encotramos a bola agora podemos brincar com ela.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}